name: gesture_handlers
description: Gesture handlers Flutter project provide reusable gesture handler and interactive transitions between routes.
version: 1.0.0+3
homepage: 'https://github.com/kyuqw/gesture_handlers'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
